language: node_js

node_js:
  - 12

services:
  - docker

before_script:
    - npm install
    - npm run create:db
    - npm run start:db
    - docker ps -a
    
script:
    - npm run test
    - npm run test:e2e